/*
 * JFrameGraficos.java
 *
 * Created on 10/05/2009, 05:27:09 PM
 */
package graficos;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author lns
 */
public class JFrameGraficos extends javax.swing.JFrame {

    private BufferedImage grafica = null;

    /**
     * Creates new form JFrameGraficos
     */
    public JFrameGraficos() {
        initComponents();
    }

    public BufferedImage creaImagen() {
        XYSeries series = new XYSeries("Tipo de Cambio mes de Octubre");
        series.add(31, 500);
        series.add(30, 500);
        series.add(29, 500);
        series.add(26, 505);
        series.add(25, 510);
        series.add(24, 508);
        series.add(23, 509);
        series.add(22, 506);
        series.add(19, 508);
        series.add(18, 505);
        series.add(17, 505);
        series.add(16, 501);
        series.add(12, 498);
        series.add(11, 501);
        series.add(10, 503);
        series.add(9, 506);
        series.add(8, 509);
        series.add(4, 510);
        series.add(3, 513);
        series.add(2, 514);
        series.add(1, 516);

        XYDataset juegoDatos = new XYSeriesCollection(series);

        JFreeChart chart = ChartFactory.createXYLineChart(
                "Tipo de Cambio mes de Octubre", // Titulo de la grafica
                "Fecha", // Leyenda Eje X
                "Valor Dolar Facturacion", // Leyenda Eje Y
                juegoDatos,
                PlotOrientation.VERTICAL,
                false,
                false,
                false);

        // Definimos el tamanio de la grafica
        BufferedImage image = chart.createBufferedImage(this.getWidth(), this.getHeight());
        return image;
    }

    @Override
    public void paint(Graphics g) {
        if (grafica == null) {
            grafica = this.creaImagen();
        }
        g.drawImage(grafica, 30, 30, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graficos Estadisticos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFrameGraficos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
